# Generated by Django 5.2.8 on 2026-01-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KARANIT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
